In [1560]:
import pandas as pd
import numpy as np

#### Planilha (xlsx): Folha de pagamento

In [1561]:
df = pd.read_excel('input\\folha_de_pagamento_072023.xlsx', header=3)
df.head()

,UF Empresa,NOME,CÓDIGO,DIV. RH,FUNÇÃO,HORAS/DIAS,(001) SALARIO NORMAL,(004) DESCANSO SEM REM (A),(010) ADICION.NOTURNO,(011) ADC INSALUBRIDADE,...,(158) CESTA BASICA ANTERIORES,(160) EMPRESTIMO,(161) SEGURO DE VIDA,(162) ASSISTENCIA MEDICA,(172) P.ALIMENTICIA S/FERIAS,(174) PENSAO ALIMENTICIA,(190) I.R.R.F.,(192) IR S/FERIAS RETIDO,(813) REFEIÇÃO (CONVÊNIO),VALOR FGTS
0,SP,A,87,011.001.002,SUPERV VENDAS JR,30,1110.834286,-,-,-,...,-,-,0.428571,-,-,-,24.205714,-,-,88.865714
1,SP,B,426,011.001.002,AUX LIMPEZA SR,30,335.432857,0.064286,-,-,...,-,-,0.428571,-,-,-,-,-,-,26.865714
2,SP,A,483,011.001.002,AUXILIAR ADM JUNIOR,30,308.321429,-,-,-,...,-,-,0.428571,41.917143,-,-,-,-,-,24.665714
3,SP,B,526,011.001.002,AUX ADMINISTRAT PLEN,30,346.672857,0.247143,-,-,...,-,-,0.428571,-,-,-,-,-,-,27.855714
4,SP,A,546,011.001.002,ASSIST SUPRIMENTO TR,30,641.96,-,-,-,...,-,-,0.428571,-,-,-,-,-,-,50.405714

In [1562]:
colunas_para_alterar = df.columns[6:63]

# Função para tratar valores "-" como nulos (NaN)
def tratar_valor(valor):
    valor = str(valor).strip()
    if valor == '-':
        return 0
    return valor

# Loop pelas colunas e aplique a função de tratamento em cada uma delas.
for coluna in colunas_para_alterar:
    df[coluna] = df[coluna].apply(tratar_valor)

for coluna in colunas_para_alterar:
   df[coluna] = df[coluna].astype('float')

df.head(20)

,UF Empresa,NOME,CÓDIGO,DIV. RH,FUNÇÃO,HORAS/DIAS,(001) SALARIO NORMAL,(004) DESCANSO SEM REM (A),(010) ADICION.NOTURNO,(011) ADC INSALUBRIDADE,...,(158) CESTA BASICA ANTERIORES,(160) EMPRESTIMO,(161) SEGURO DE VIDA,(162) ASSISTENCIA MEDICA,(172) P.ALIMENTICIA S/FERIAS,(174) PENSAO ALIMENTICIA,(190) I.R.R.F.,(192) IR S/FERIAS RETIDO,(813) REFEIÇÃO (CONVÊNIO),VALOR FGTS
0,SP,A,87,011.001.002,SUPERV VENDAS JR,30,1110.834286,0.000000,0.0,0.000000,...,0.0,0.000000,0.428571,0.000000,0.0,0.0,24.205714,0.000000,0.0,88.865714
1,SP,B,426,011.001.002,AUX LIMPEZA SR,30,335.432857,0.064286,0.0,0.000000,...,0.0,0.000000,0.428571,0.000000,0.0,0.0,0.000000,0.000000,0.0,26.865714
2,SP,A,483,011.001.002,AUXILIAR ADM JUNIOR,30,308.321429,0.000000,0.0,0.000000,...,0.0,0.000000,0.428571,41.917143,0.0,0.0,0.000000,0.000000,0.0,24.665714
3,SP,B,526,011.001.002,AUX ADMINISTRAT PLEN,30,346.672857,0.247143,0.0,0.000000,...,0.0,0.000000,0.428571,0.000000,0.0,0.0,0.000000,0.000000,0.0,27.855714
4,SP,A,546,011.001.002,ASSIST SUPRIMENTO TR,30,641.960000,0.000000,0.0,0.000000,...,0.0,0.000000,0.428571,0.000000,0.0,0.0,0.000000,0.000000,0.0,50.405714
5,SP,B,555,011.001.002,AUX ADMINIST I JR,16,159.134286,0.000000,0.0,0.000000,...,0.0,0.000000,0.428571,0.000000,0.0,0.0,0.000000,0.000000,0.0,29.274286
6,SP,A,567,011.001.002,AUX ADMINISTRAT PLEN,30,346.672857,0.190000,0.0,0.000000,...,0.0,0.000000,0.428571,0.000000,0.0,0.0,0.000000,0.000000,0.0,27.808571
7,SP,B,568,011.001.002,APRENDIZ ADMINISTRAT,30,260.784286,0.000000,0.0,0.000000,...,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.0,5.214286
8,SP,A,348,011.001.004,COLORISTA SR,30,606.224286,0.000000,0.0,0.000000,...,0.0,0.000000,0.428571,0.000000,0.0,0.0,0.000000,0.000000,0.0,47.550000
9,SP,B,364,011.001.004,COORD CONT QUALID PL,30,741.530000,0.000000,0.0,37.271429,...,0.0,0.000000,0.428571,0.000000,0.0,0.0,6.662857,0.000000,0.0,61.607143
10,SP,A,447,011.001.004,Coord P&D Pleno,30,815.592857,0.000000,0.0,0.000000,...,0.0,57.142857,0.428571,0.000000,0.0,0.0,5.342857,0.000000,0.0,65.247143
11,SP,B,512,011.001.004,ASSIST LABORAT SR,30,606.225714,0.000000,0.0,0.000000,...,0.0,0.000000,0.428571,0.000000,0.0,0.0,0.000000,0.000000,0.0,48.464286
12,SP,A,540,011.001.004,COLORISTA JR,30,456.232857,0.190000,0.0,0.000000,...,0.0,0.000000,0.428571,0.000000,0.0,0.0,0.000000,0.000000,0.0,36.570000
13,SP,B,543,011.001.004,SUP DESENVOLVIM JR,30,1390.875714,0.000000,0.0,0.000000,...,0.0,0.000000,0.428571,116.112857,0.0,0.0,61.171429,0.000000,0.0,111.270000
14,SP,A,544,011.001.004,COLORISTA MASTER,30,697.160000,0.000000,0.0,0.000000,...,0.0,0.000000,0.428571,0.000000,0.0,0.0,2.260000,0.000000,0.0,54.890000
15,SP,B,548,011.001.004,ASSIST LABORAT PL,30,521.847143,0.000000,0.0,0.000000,...,0.0,0.000000,0.428571,0.000000,0.0,0.0,0.000000,0.000000,0.0,41.342857
16,SP,A,558,011.001.004,ASSIST LABORAT JR,30,456.231429,0.000000,0.0,0.000000,...,0.0,0.000000,0.428571,0.000000,0.0,0.0,0.000000,0.000000,0.0,36.497143
17,SP,B,270,011.001.007,ENCARREG PRODUCAO JR,11,239.172857,0.000000,0.0,12.827143,...,0.0,57.142857,0.428571,0.000000,0.0,0.0,0.000000,31.728571,0.0,71.184286
18,SP,A,396,011.001.007,Lider Equipe Prod Sr,30,566.538571,0.354286,0.0,37.714286,...,0.0,0.000000,0.428571,0.000000,0.0,0.0,0.000000,0.000000,0.0,48.514286
19,SP,B,490,011.001.007,Prep de Tintas Pleno,30,348.110000,0.000000,0.0,37.691429,...,0.0,0.000000,0.428571,0.000000,0.0,0.0,0.000000,0.000000,0.0,30.847143

In [1563]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 72 entries, 0 to 71
Data columns (total 62 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   UF Empresa                            72 non-null     object
 1   NOME                                  72 non-null     object
 2   CÓDIGO                                72 non-null     int64
 3   DIV. RH                               72 non-null     object
 4   FUNÇÃO                                72 non-null     object
 5   HORAS/DIAS                            72 non-null     object
 6   (001) SALARIO NORMAL                  72 non-null     float64
 7   (004) DESCANSO SEM REM (A)            72 non-null     float64
 8   (010) ADICION.NOTURNO                 72 non-null     float64
 9   (011) ADC INSALUBRIDADE               72 non-null     float64
 10  (012) ADC PERICULOSIDADE              72 non-null     float64
 11  (015) FERIAS                          72 non-null     float64
 12  (016) ABONO DE FERIAS                 72 non-null     float64
 13  (017) ADIC 1/3 DE FERIAS              72 non-null     float64
 14  (018) ADIC 1/3 FERIAS ABON            72 non-null     float64
 15  (025) PARTICIPACAO LUCROS             72 non-null     float64
 16  (030) HORA EXTRA 70%                  72 non-null     float64
 17  (033) HORA EXTRA 110%                 72 non-null     float64
 18  (040) HORA EXTRA NOTURNA 70%          72 non-null     float64
 19  (041) HORA EXTRA NOTURNA 110%         72 non-null     float64
 20  (050) AUXILIO SEGURO                  72 non-null     float64
 21  (051) SAL QUITACAO - DEMIS            72 non-null     float64
 22  (055) 13o PROPORC -DEMISS             72 non-null     float64
 23  (057) 13o INDEN.AV.PV.1/12            72 non-null     float64
 24  (067) FERIAS INDENIZADAS              72 non-null     float64
 25  (068) FERIAS 1/3                      72 non-null     float64
 26  (069) AVISO PREVIO INDEN.             72 non-null     float64
 27  (086) FERIAS AV PREVIO INDENIZADO     72 non-null     float64
 28  (087) 1/3 FERIAS AV PREVIO INDENIZAD  72 non-null     float64
 29  (098) HE INTRAJORNADA                 72 non-null     float64
 30  (100) ARREDONDAMENT DO MES            72 non-null     float64
 31  (267) FÉRIAS PROPORCIONAIS            72 non-null     float64
 32  (268) 1/3 FÉRIAS PROPORCIONAIS        72 non-null     float64
 33  (101) I.N.S.S                         72 non-null     float64
 34  (102) I.N.S.S S/FERIAS                72 non-null     float64
 35  (103) INSS S/13o SALARIO              72 non-null     float64
 36  (105) CARTAO ALIMENTACAO              72 non-null     float64
 37  (111) ADIANT AUTOMATICO               72 non-null     float64
 38  (113) TROCO ANTERIOR                  72 non-null     float64
 39  (115) FERIAS                          72 non-null     float64
 40  (116) ABONO DE FERIAS                 72 non-null     float64
 41  (123) CESTA BASICA                    72 non-null     float64
 42  (125) REFEICAO                        72 non-null     float64
 43  (139) CONVENIO FARMACIA ANTERIORES    72 non-null     float64
 44  (141) DESC.HORAS                      72 non-null     float64
 45  (142) FALTAS                          72 non-null     float64
 46  (144) VALE TRANSPORTE (V)             72 non-null     float64
 47  (145) VALE TRANSPORTE (P)             72 non-null     float64
 48  (150) AUXILIO SEGURO                  72 non-null     float64
 49  (152) LIQUIDO QUITACAO                72 non-null     float64
 50  (153) CONVENIO FARMACIA               72 non-null     float64
 51  (157) DIF.PENSAO ALIMENTICIA          72 non-null     float64
 52  (158) CESTA BASICA ANTERIORES         72 non-null     float64
 53  (160) EMPRESTIMO                      72 non-null     float64
 54  (161) SEGURO DE VIDA                  72 non-null     float64
 55  (162) ASSISTENCIA MEDICA              72 non-null     float64
 56  (172) P.ALIMENTICIA S/FERIAS          72 non-null     float64
 57  (174) PENSAO ALIMENTICIA              72 non-null     float64
 58  (190) I.R.R.F.                        72 non-null     float64
 59  (192) IR S/FERIAS RETIDO              72 non-null     float64
 60  (813) REFEIÇÃO (CONVÊNIO)             72 non-null     float64
 61  VALOR FGTS                            72 non-null     float64
dtypes: float64(56), int64(1), object(5)
memory usage: 35.0+ KB

In [1564]:
colunas_para_somar = df.iloc[:, 6:]
soma_colunas = colunas_para_somar.sum().round(2)
soma_total = soma_colunas.sum()

# Crie um novo DataFrame para mostrar a soma das colunas.
df_soma = pd.DataFrame({'Coluna': soma_colunas.index, 'Soma': soma_colunas.values})

print(soma_total)

print(df_soma)

67272.05
                                  Coluna      Soma
0                   (001) SALARIO NORMAL  30485.60
1             (004) DESCANSO SEM REM (A)    395.32
2                  (010) ADICION.NOTURNO    611.63
3                (011) ADC INSALUBRIDADE    539.19
4               (012) ADC PERICULOSIDADE    936.47
5                           (015) FERIAS   2426.69
6                  (016) ABONO DE FERIAS    215.09
7               (017) ADIC 1/3 DE FERIAS    808.90
8             (018) ADIC 1/3 FERIAS ABON     71.70
9              (025) PARTICIPACAO LUCROS    182.50
10                  (030) HORA EXTRA 70%    513.10
11                 (033) HORA EXTRA 110%    733.57
12          (040) HORA EXTRA NOTURNA 70%    188.49
13         (041) HORA EXTRA NOTURNA 110%      3.50
14                  (050) AUXILIO SEGURO    171.19
15            (051) SAL QUITACAO - DEMIS    308.11
16             (055) 13o PROPORC -DEMISS    223.82
17            (057) 13o INDEN.AV.PV.1/12     31.97
18              (067) FERIAS INDENIZADAS    440.11
19                      (068) FERIAS 1/3    146.70
20             (069) AVISO PREVIO INDEN.    528.14
21     (086) FERIAS AV PREVIO INDENIZADO     33.13
22  (087) 1/3 FERIAS AV PREVIO INDENIZAD     11.04
23                 (098) HE INTRAJORNADA      8.14
24            (100) ARREDONDAMENT DO MES      4.71
25            (267) FÉRIAS PROPORCIONAIS     33.13
26        (268) 1/3 FÉRIAS PROPORCIONAIS     11.04
27                         (101) I.N.S.S   3341.27
28                (102) I.N.S.S S/FERIAS    320.23
29              (103) INSS S/13o SALARIO     20.19
30              (105) CARTAO ALIMENTACAO     85.11
31               (111) ADIANT AUTOMATICO  11911.52
32                  (113) TROCO ANTERIOR      4.45
33                          (115) FERIAS   2761.80
34                 (116) ABONO DE FERIAS    286.78
35                    (123) CESTA BASICA    157.26
36                        (125) REFEICAO    600.91
37    (139) CONVENIO FARMACIA ANTERIORES     42.29
38                      (141) DESC.HORAS     94.09
39                          (142) FALTAS      9.35
40             (144) VALE TRANSPORTE (V)     17.36
41             (145) VALE TRANSPORTE (P)    183.51
42                  (150) AUXILIO SEGURO    171.19
43                (152) LIQUIDO QUITACAO   1856.06
44               (153) CONVENIO FARMACIA    254.58
45          (157) DIF.PENSAO ALIMENTICIA     19.26
46         (158) CESTA BASICA ANTERIORES      6.86
47                      (160) EMPRESTIMO    556.35
48                  (161) SEGURO DE VIDA     29.57
49              (162) ASSISTENCIA MEDICA    202.16
50          (172) P.ALIMENTICIA S/FERIAS     15.36
51              (174) PENSAO ALIMENTICIA    198.42
52                        (190) I.R.R.F.    377.58
53              (192) IR S/FERIAS RETIDO    138.21
54             (813) REFEIÇÃO (CONVÊNIO)     22.86
55                            VALOR FGTS   3524.49

#### Planilhas (.csv): Utilitários para transformação

In [1565]:
df_centro_trabalho = pd.read_csv('utils\centro_de_trabalho.csv', encoding='ISO-8859-1')

##### Parte 1: Associação e verificação do centro de trabalho

In [1566]:
df_centro_trabalho.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19 entries, 0 to 18
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   DIV. RH             19 non-null     int64
 1   DEPARTAMENTO        19 non-null     object
 2   CENTRO DE CUSTO     19 non-null     object
 3   CR                  19 non-null     object
 4   UNIDADE DE NEGOCIO  19 non-null     object
dtypes: int64(1), object(4)
memory usage: 892.0+ bytes

In [1567]:
df['DIV. RH'] = df['DIV. RH'].str.replace('.', '')
df['DIV. RH'] = df['DIV. RH'].astype('int64')
df['DIV. RH'].head()

0    11001002
1    11001002
2    11001002
3    11001002
4    11001002
Name: DIV. RH, dtype: int64

In [1568]:
df = df.merge(df_centro_trabalho[['DIV. RH', 'CENTRO DE CUSTO', 'CR', 'UNIDADE DE NEGOCIO']], on='DIV. RH', how='left')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 72 entries, 0 to 71
Data columns (total 65 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   UF Empresa                            72 non-null     object
 1   NOME                                  72 non-null     object
 2   CÓDIGO                                72 non-null     int64
 3   DIV. RH                               72 non-null     int64
 4   FUNÇÃO                                72 non-null     object
 5   HORAS/DIAS                            72 non-null     object
 6   (001) SALARIO NORMAL                  72 non-null     float64
 7   (004) DESCANSO SEM REM (A)            72 non-null     float64
 8   (010) ADICION.NOTURNO                 72 non-null     float64
 9   (011) ADC INSALUBRIDADE               72 non-null     float64
 10  (012) ADC PERICULOSIDADE              72 non-null     float64
 11  (015) FERIAS                          72 non-null     float64
 12  (016) ABONO DE FERIAS                 72 non-null     float64
 13  (017) ADIC 1/3 DE FERIAS              72 non-null     float64
 14  (018) ADIC 1/3 FERIAS ABON            72 non-null     float64
 15  (025) PARTICIPACAO LUCROS             72 non-null     float64
 16  (030) HORA EXTRA 70%                  72 non-null     float64
 17  (033) HORA EXTRA 110%                 72 non-null     float64
 18  (040) HORA EXTRA NOTURNA 70%          72 non-null     float64
 19  (041) HORA EXTRA NOTURNA 110%         72 non-null     float64
 20  (050) AUXILIO SEGURO                  72 non-null     float64
 21  (051) SAL QUITACAO - DEMIS            72 non-null     float64
 22  (055) 13o PROPORC -DEMISS             72 non-null     float64
 23  (057) 13o INDEN.AV.PV.1/12            72 non-null     float64
 24  (067) FERIAS INDENIZADAS              72 non-null     float64
 25  (068) FERIAS 1/3                      72 non-null     float64
 26  (069) AVISO PREVIO INDEN.             72 non-null     float64
 27  (086) FERIAS AV PREVIO INDENIZADO     72 non-null     float64
 28  (087) 1/3 FERIAS AV PREVIO INDENIZAD  72 non-null     float64
 29  (098) HE INTRAJORNADA                 72 non-null     float64
 30  (100) ARREDONDAMENT DO MES            72 non-null     float64
 31  (267) FÉRIAS PROPORCIONAIS            72 non-null     float64
 32  (268) 1/3 FÉRIAS PROPORCIONAIS        72 non-null     float64
 33  (101) I.N.S.S                         72 non-null     float64
 34  (102) I.N.S.S S/FERIAS                72 non-null     float64
 35  (103) INSS S/13o SALARIO              72 non-null     float64
 36  (105) CARTAO ALIMENTACAO              72 non-null     float64
 37  (111) ADIANT AUTOMATICO               72 non-null     float64
 38  (113) TROCO ANTERIOR                  72 non-null     float64
 39  (115) FERIAS                          72 non-null     float64
 40  (116) ABONO DE FERIAS                 72 non-null     float64
 41  (123) CESTA BASICA                    72 non-null     float64
 42  (125) REFEICAO                        72 non-null     float64
 43  (139) CONVENIO FARMACIA ANTERIORES    72 non-null     float64
 44  (141) DESC.HORAS                      72 non-null     float64
 45  (142) FALTAS                          72 non-null     float64
 46  (144) VALE TRANSPORTE (V)             72 non-null     float64
 47  (145) VALE TRANSPORTE (P)             72 non-null     float64
 48  (150) AUXILIO SEGURO                  72 non-null     float64
 49  (152) LIQUIDO QUITACAO                72 non-null     float64
 50  (153) CONVENIO FARMACIA               72 non-null     float64
 51  (157) DIF.PENSAO ALIMENTICIA          72 non-null     float64
 52  (158) CESTA BASICA ANTERIORES         72 non-null     float64
 53  (160) EMPRESTIMO                      72 non-null     float64
 54  (161) SEGURO DE VIDA                  72 non-null     float64
 55  (162) ASSISTENCIA MEDICA              72 non-null     float64
 56  (172) P.ALIMENTICIA S/FERIAS          72 non-null     float64
 57  (174) PENSAO ALIMENTICIA              72 non-null     float64
 58  (190) I.R.R.F.                        72 non-null     float64
 59  (192) IR S/FERIAS RETIDO              72 non-null     float64
 60  (813) REFEIÇÃO (CONVÊNIO)             72 non-null     float64
 61  VALOR FGTS                            72 non-null     float64
 62  CENTRO DE CUSTO                       72 non-null     object
 63  CR                                    72 non-null     object
 64  UNIDADE DE NEGOCIO                    72 non-null     object
dtypes: float64(56), int64(2), object(7)
memory usage: 36.7+ KB

In [1569]:
df['SITUAÇÃO'] = df['CENTRO DE CUSTO'].str.cat(df['CR'])
df['SITUAÇÃO'].head()

0    admCR1002
1    admCR1002
2    admCR1002
3    admCR1002
4    admCR1002
Name: SITUAÇÃO, dtype: object

In [1570]:
total_registros = df['DIV. RH'].count()
total_situacao = df['SITUAÇÃO'].count()


if total_situacao == total_registros:
    print(f'São {total_registros} registros em "DIV. RH".')
    print(f'Sucesso!. Todos os registros foram classificados em "SITUAÇÃO')
else:
    print(f'São {total_registros} registros em "DIV. RH".')
    print(f'Incosistência!. Dos {total_registros} registros, {total_situacao} foram classificados em "SITUAÇÃO".')

São 72 registros em "DIV. RH".
Sucesso!. Todos os registros foram classificados em "SITUAÇÃO

In [1571]:
quantidade_com_nulos_situacao = df['SITUAÇÃO'].isnull()

print(f'Existem {quantidade_com_nulos_situacao.sum()} registros que não foram corretamente classificados em "SITUAÇÃO".')

Existem 0 registros que não foram corretamente classificados em "SITUAÇÃO".

In [1572]:
valores_nulos_situacao = df[df['SITUAÇÃO'].isnull()]

In [1573]:
linhas_com_nulos_situacao = valores_nulos_situacao[['CÓDIGO', 'DIV. RH', 'CENTRO DE CUSTO', 'CR', 'SITUAÇÃO']]

print(f'Veja a relação a seguir: \n \n {linhas_com_nulos_situacao}')

Veja a relação a seguir:

 Empty DataFrame
Columns: [CÓDIGO, DIV. RH, CENTRO DE CUSTO, CR, SITUAÇÃO]
Index: []

In [1574]:
#valores_unicos_situacao = df['SITUAÇÃO'].unique()
quantidade_situacao = df['SITUAÇÃO'].value_counts() 
quantidade_unidades_negocio = df['UNIDADE DE NEGOCIO'].value_counts()

In [1575]:
quantidade_situacao

SITUAÇÃO
custoCR2016       28
admCR1002          8
custoCR3020        6
custoCR3006        5
custoCR3009        5
custoCR3014        5
custoCR3013        3
comCR2020          2
custoCR3004        2
custoCR3011        2
custoCR3010        2
custoCR4004        2
custoCR2015Rat     1
custoCR2015        1
Name: count, dtype: int64

In [1576]:
quantidade_unidades_negocio

UNIDADE DE NEGOCIO
UN03    68
UN01     2
UN04     2
Name: count, dtype: int64

##### Parte 2: Planilha resumo por CR e SITUAÇÃO

In [1577]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 72 entries, 0 to 71
Data columns (total 66 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   UF Empresa                            72 non-null     object
 1   NOME                                  72 non-null     object
 2   CÓDIGO                                72 non-null     int64
 3   DIV. RH                               72 non-null     int64
 4   FUNÇÃO                                72 non-null     object
 5   HORAS/DIAS                            72 non-null     object
 6   (001) SALARIO NORMAL                  72 non-null     float64
 7   (004) DESCANSO SEM REM (A)            72 non-null     float64
 8   (010) ADICION.NOTURNO                 72 non-null     float64
 9   (011) ADC INSALUBRIDADE               72 non-null     float64
 10  (012) ADC PERICULOSIDADE              72 non-null     float64
 11  (015) FERIAS                          72 non-null     float64
 12  (016) ABONO DE FERIAS                 72 non-null     float64
 13  (017) ADIC 1/3 DE FERIAS              72 non-null     float64
 14  (018) ADIC 1/3 FERIAS ABON            72 non-null     float64
 15  (025) PARTICIPACAO LUCROS             72 non-null     float64
 16  (030) HORA EXTRA 70%                  72 non-null     float64
 17  (033) HORA EXTRA 110%                 72 non-null     float64
 18  (040) HORA EXTRA NOTURNA 70%          72 non-null     float64
 19  (041) HORA EXTRA NOTURNA 110%         72 non-null     float64
 20  (050) AUXILIO SEGURO                  72 non-null     float64
 21  (051) SAL QUITACAO - DEMIS            72 non-null     float64
 22  (055) 13o PROPORC -DEMISS             72 non-null     float64
 23  (057) 13o INDEN.AV.PV.1/12            72 non-null     float64
 24  (067) FERIAS INDENIZADAS              72 non-null     float64
 25  (068) FERIAS 1/3                      72 non-null     float64
 26  (069) AVISO PREVIO INDEN.             72 non-null     float64
 27  (086) FERIAS AV PREVIO INDENIZADO     72 non-null     float64
 28  (087) 1/3 FERIAS AV PREVIO INDENIZAD  72 non-null     float64
 29  (098) HE INTRAJORNADA                 72 non-null     float64
 30  (100) ARREDONDAMENT DO MES            72 non-null     float64
 31  (267) FÉRIAS PROPORCIONAIS            72 non-null     float64
 32  (268) 1/3 FÉRIAS PROPORCIONAIS        72 non-null     float64
 33  (101) I.N.S.S                         72 non-null     float64
 34  (102) I.N.S.S S/FERIAS                72 non-null     float64
 35  (103) INSS S/13o SALARIO              72 non-null     float64
 36  (105) CARTAO ALIMENTACAO              72 non-null     float64
 37  (111) ADIANT AUTOMATICO               72 non-null     float64
 38  (113) TROCO ANTERIOR                  72 non-null     float64
 39  (115) FERIAS                          72 non-null     float64
 40  (116) ABONO DE FERIAS                 72 non-null     float64
 41  (123) CESTA BASICA                    72 non-null     float64
 42  (125) REFEICAO                        72 non-null     float64
 43  (139) CONVENIO FARMACIA ANTERIORES    72 non-null     float64
 44  (141) DESC.HORAS                      72 non-null     float64
 45  (142) FALTAS                          72 non-null     float64
 46  (144) VALE TRANSPORTE (V)             72 non-null     float64
 47  (145) VALE TRANSPORTE (P)             72 non-null     float64
 48  (150) AUXILIO SEGURO                  72 non-null     float64
 49  (152) LIQUIDO QUITACAO                72 non-null     float64
 50  (153) CONVENIO FARMACIA               72 non-null     float64
 51  (157) DIF.PENSAO ALIMENTICIA          72 non-null     float64
 52  (158) CESTA BASICA ANTERIORES         72 non-null     float64
 53  (160) EMPRESTIMO                      72 non-null     float64
 54  (161) SEGURO DE VIDA                  72 non-null     float64
 55  (162) ASSISTENCIA MEDICA              72 non-null     float64
 56  (172) P.ALIMENTICIA S/FERIAS          72 non-null     float64
 57  (174) PENSAO ALIMENTICIA              72 non-null     float64
 58  (190) I.R.R.F.                        72 non-null     float64
 59  (192) IR S/FERIAS RETIDO              72 non-null     float64
 60  (813) REFEIÇÃO (CONVÊNIO)             72 non-null     float64
 61  VALOR FGTS                            72 non-null     float64
 62  CENTRO DE CUSTO                       72 non-null     object
 63  CR                                    72 non-null     object
 64  UNIDADE DE NEGOCIO                    72 non-null     object
 65  SITUAÇÃO                              72 non-null     object
dtypes: float64(56), int64(2), object(8)
memory usage: 37.3+ KB

In [1578]:
resumo = df[['CR', 'SITUAÇÃO', 'UNIDADE DE NEGOCIO']].copy()
resumo = resumo.drop_duplicates()
resumo.info()

<class 'pandas.core.frame.DataFrame'>
Index: 14 entries, 0 to 71
Data columns (total 3 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   CR                  14 non-null     object
 1   SITUAÇÃO            14 non-null     object
 2   UNIDADE DE NEGOCIO  14 non-null     object
dtypes: object(3)
memory usage: 448.0+ bytes

In [1579]:
resumo.head()

        CR     SITUAÇÃO UNIDADE DE NEGOCIO
0   CR1002    admCR1002               UN03
8   CR2016  custoCR2016               UN03
36  CR2020    comCR2020               UN03
38  CR3004  custoCR3004               UN03
40  CR3011  custoCR3011               UN03

In [1580]:
colunas_float = df.select_dtypes(include='float64').columns.tolist()
#colunas_float = df.select_dtypes(include='float64')
colunas_condicionais = ['CR', 'SITUAÇÃO', 'UNIDADE DE NEGOCIO']
colunas_relevantes = df[colunas_float + colunas_condicionais]
#soma_condicional = colunas_float.groupby(df['CR', 'SITUAÇÃO']).sum()
soma_condicional = colunas_relevantes.groupby(colunas_condicionais).sum()

In [1581]:
soma_condicional.head()

,,,(001) SALARIO NORMAL,(004) DESCANSO SEM REM (A),(010) ADICION.NOTURNO,(011) ADC INSALUBRIDADE,(012) ADC PERICULOSIDADE,(015) FERIAS,(016) ABONO DE FERIAS,(017) ADIC 1/3 DE FERIAS,(018) ADIC 1/3 FERIAS ABON,(025) PARTICIPACAO LUCROS,...,(158) CESTA BASICA ANTERIORES,(160) EMPRESTIMO,(161) SEGURO DE VIDA,(162) ASSISTENCIA MEDICA,(172) P.ALIMENTICIA S/FERIAS,(174) PENSAO ALIMENTICIA,(190) I.R.R.F.,(192) IR S/FERIAS RETIDO,(813) REFEIÇÃO (CONVÊNIO),VALOR FGTS
CR,SITUAÇÃO,UNIDADE DE NEGOCIO,,,,,,,,,,,,,,,,,,,,,
CR1002,admCR1002,UN03,3509.812857,0.501429,0.0,0.000000,0.000000,155.345714,0.000000,51.782857,0.000000,0.0,...,0.000000,0.000000,3.000000,41.917143,0.0,0.000000,24.205714,0.000000,0.000000,280.955714
CR2015,custoCR2015,UN04,638.042857,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,...,0.000000,0.000000,0.428571,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,51.042857
CR2015Rat,custoCR2015Rat,UN04,674.032857,1.572857,0.0,37.714286,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,...,0.000000,0.000000,0.428571,0.000000,0.0,0.000000,3.521429,0.000000,0.000000,57.718571
CR2016,custoCR2016,UN03,14800.851429,54.378571,0.0,501.474286,456.985714,1074.691429,170.022857,358.230000,56.674286,0.0,...,6.857143,157.142857,11.142857,116.112857,0.0,129.067143,242.051429,93.111429,0.000000,1432.921429
CR2020,comCR2020,UN03,890.854286,28.875714,0.0,0.000000,267.170000,0.000000,0.000000,0.000000,0.000000,0.0,...,0.000000,142.857143,0.857143,0.000000,0.0,0.000000,23.662857,0.000000,22.857143,106.938571

In [1582]:
soma_condicional['Valor Total'] = soma_condicional.sum(axis=1)
resultado_situacao = soma_condicional[['Valor Total']].round(2)
resultado = resultado_situacao['Valor Total'].sum()

print(type(resultado_situacao))
print(resultado)
print(resultado_situacao)

<class 'pandas.core.frame.DataFrame'>
67272.05
                                             Valor Total
CR        SITUAÇÃO       UNIDADE DE NEGOCIO
CR1002    admCR1002      UN03                    6111.06
CR2015    custoCR2015    UN04                    1012.75
CR2015Rat custoCR2015Rat UN04                    1145.47
CR2016    custoCR2016    UN03                   29917.99
CR2020    comCR2020      UN03                    2139.28
CR3004    custoCR3004    UN03                    1454.44
CR3006    custoCR3006    UN03                    4673.59
CR3009    custoCR3009    UN03                    3301.58
CR3010    custoCR3010    UN03                    1005.17
CR3011    custoCR3011    UN03                    1050.00
CR3013    custoCR3013    UN03                    2025.04
CR3014    custoCR3014    UN03                    3832.19
CR3020    custoCR3020    UN03                    8073.75
CR4004    custoCR4004    UN01                    1529.74

In [1583]:
resumo = soma_condicional.reset_index()
resumo

,CR,SITUAÇÃO,UNIDADE DE NEGOCIO,(001) SALARIO NORMAL,(004) DESCANSO SEM REM (A),(010) ADICION.NOTURNO,(011) ADC INSALUBRIDADE,(012) ADC PERICULOSIDADE,(015) FERIAS,(016) ABONO DE FERIAS,...,(160) EMPRESTIMO,(161) SEGURO DE VIDA,(162) ASSISTENCIA MEDICA,(172) P.ALIMENTICIA S/FERIAS,(174) PENSAO ALIMENTICIA,(190) I.R.R.F.,(192) IR S/FERIAS RETIDO,(813) REFEIÇÃO (CONVÊNIO),VALOR FGTS,Valor Total
0,CR1002,admCR1002,UN03,3509.812857,0.501429,0.000000,0.000000,0.000000,155.345714,0.000000,...,0.000000,3.000000,41.917143,0.00,0.000000,24.205714,0.000000,0.000000,280.955714,6111.064286
1,CR2015,custoCR2015,UN04,638.042857,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.428571,0.000000,0.00,0.000000,0.000000,0.000000,0.000000,51.042857,1012.748571
2,CR2015Rat,custoCR2015Rat,UN04,674.032857,1.572857,0.000000,37.714286,0.000000,0.000000,0.000000,...,0.000000,0.428571,0.000000,0.00,0.000000,3.521429,0.000000,0.000000,57.718571,1145.472857
3,CR2016,custoCR2016,UN03,14800.851429,54.378571,0.000000,501.474286,456.985714,1074.691429,170.022857,...,157.142857,11.142857,116.112857,0.00,129.067143,242.051429,93.111429,0.000000,1432.921429,29917.990000
4,CR2020,comCR2020,UN03,890.854286,28.875714,0.000000,0.000000,267.170000,0.000000,0.000000,...,142.857143,0.857143,0.000000,0.00,0.000000,23.662857,0.000000,22.857143,106.938571,2139.281429
5,CR3004,custoCR3004,UN03,875.591429,7.422857,29.510000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.857143,0.000000,0.00,0.000000,0.000000,0.000000,0.000000,73.715714,1454.438571
6,CR3006,custoCR3006,UN03,1549.087143,103.311429,141.101429,0.000000,0.000000,468.911429,0.000000,...,0.000000,2.142857,0.000000,0.00,0.000000,64.077143,14.422857,0.000000,224.761429,4673.587143
7,CR3009,custoCR3009,UN03,1786.547143,58.928571,139.888571,0.000000,0.000000,0.000000,0.000000,...,0.000000,2.142857,0.000000,0.00,0.000000,9.305714,0.000000,0.000000,170.945714,3301.582857
8,CR3010,custoCR3010,UN03,579.520000,12.540000,33.481429,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.857143,0.000000,0.00,0.000000,0.000000,0.000000,0.000000,52.544286,1005.167143
9,CR3011,custoCR3011,UN03,616.222857,4.761429,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.857143,0.000000,0.00,0.000000,0.000000,0.000000,0.000000,51.518571,1049.998571
10,CR3013,custoCR3013,UN03,933.454286,29.780000,23.900000,0.000000,0.000000,57.597143,0.000000,...,59.524286,1.285714,0.000000,15.36,69.354286,0.000000,1.045714,0.000000,95.470000,2025.038571
11,CR3014,custoCR3014,UN03,1239.802857,49.578571,128.020000,0.000000,0.000000,450.627143,45.062857,...,134.920000,2.142857,44.125714,0.00,0.000000,6.887143,24.261429,0.000000,171.812857,3832.192857
12,CR3020,custoCR3020,UN03,1680.244286,30.295714,115.725714,0.000000,0.000000,219.521429,0.000000,...,61.904286,2.571429,0.000000,0.00,0.000000,3.871429,5.367143,0.000000,673.905714,8073.745714
13,CR4004,custoCR4004,UN01,711.531429,13.375714,0.000000,0.000000,212.314286,0.000000,0.000000,...,0.000000,0.857143,0.000000,0.00,0.000000,0.000000,0.000000,0.000000,80.234286,1529.742857

##### Parte 3: Planilha resumo por CENTRO DE CUSTO

In [1584]:
df_codigos = pd.read_csv('utils\\codigos.csv', encoding='ISO-8859-1')
df_codigos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 168 entries, 0 to 167
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   COLUNA DA FOLHA  168 non-null    object
 1   CÓDIGO 1         159 non-null    object
 2   CÓDIGO 2         159 non-null    object
 3   DESCRIÇÃO        159 non-null    object
 4   CENTRO DE CUSTO  159 non-null    object
dtypes: object(5)
memory usage: 6.7+ KB

In [1585]:
df_codigos['CENTRO DE CUSTO'].value_counts()

CENTRO DE CUSTO
custo    56
adm      53
com      50
Name: count, dtype: int64

In [1586]:
valores = df_codigos.loc[df_codigos['CENTRO DE CUSTO'] == 'custo']
#valores_adm.set_index('COLUNA DA FOLHA')
valores.head()

,COLUNA DA FOLHA,CÓDIGO 1,CÓDIGO 2,DESCRIÇÃO,CENTRO DE CUSTO
103,(001) SALARIO NORMAL,3.3.2.01.01.010,2.1.2.02.01.015,P/ VLR DE CUSTO,custo
104,(004) DESCANSO SEM REM (A),3.3.2.01.01.010,2.1.2.02.01.015,P/ VLR DE CUSTO,custo
105,(010) ADICION.NOTURNO,3.3.2.01.01.010,2.1.2.02.01.015,P/ VLR DE CUSTO,custo
106,(011) ADC INSALUBRIDADE,3.3.2.01.01.010,2.1.2.02.01.015,P/ VLR DE CUSTO,custo
107,(012) ADC PERICULOSIDADE,3.3.2.01.01.010,2.1.2.02.01.015,P/ VLR DE CUSTO,custo

In [1587]:
def associar_valor(cr_desejado):
    data = resumo.set_index('CR')
    resultados = pd.DataFrame(columns=['DATA', 'TIPO', 'DEBITO', 'CREDITO', 'DESCRICAO COMPLETA', 'VALOR', 'UNIDADE DE NEGOCIO', 'CR'])

    if cr_desejado == 'CR1002':
        codigos = df_codigos.loc[df_codigos['CENTRO DE CUSTO'] == 'adm']
    elif cr_desejado == 'CR2020':
        codigos = df_codigos.loc[df_codigos['CENTRO DE CUSTO'] == 'com']
    else:
        codigos = df_codigos.loc[df_codigos['CENTRO DE CUSTO'] == 'custo']

    for index, linha in codigos.iterrows():
        codigo1_correspondente = linha['CÓDIGO 1']
        codigo2_correspondente = linha['CÓDIGO 2']
        descricao_correspondente = linha['DESCRIÇÃO']
        folha_correspondente = linha['COLUNA DA FOLHA']
        valor_correspondente = data.loc[cr_desejado, folha_correspondente]
        unidade_correspondente = data.loc[cr_desejado, 'UNIDADE DE NEGOCIO']
        ref_completa = f'{descricao_correspondente} {folha_correspondente}'

        if valor_correspondente > 0:
            resultados.loc[len(resultados)] = ['31/07/2023', 'MANUAL', codigo1_correspondente, codigo2_correspondente, ref_completa, valor_correspondente, unidade_correspondente, cr_desejado]
        else:
            resultados = resultados

    return resultados

In [1588]:
associar_valor('CR1002')

,DATA,TIPO,DEBITO,CREDITO,DESCRICAO COMPLETA,VALOR,UNIDADE DE NEGOCIO,CR
0,31/07/2023,MANUAL,3.3.2.01.01.010,2.1.2.02.01.015,P/ VLR DE DESP ADMINISTRATIVO (001) SALARIO NO...,3509.812857,UN03,CR1002
1,31/07/2023,MANUAL,3.3.2.01.01.010,2.1.2.02.01.015,P/ VLR DE DESP ADMINISTRATIVO (004) DESCANSO S...,0.501429,UN03,CR1002
2,31/07/2023,MANUAL,2.1.2.02.02.010,2.1.2.02.01.015,P/ VLR DE DESP ADMINISTRATIVO (015) FERIAS,155.345714,UN03,CR1002
3,31/07/2023,MANUAL,2.1.2.02.02.010,2.1.2.02.01.015,P/ VLR DE DESP ADMINISTRATIVO (017) ADIC 1/3 D...,51.782857,UN03,CR1002
4,31/07/2023,MANUAL,3.3.2.01.01.010,2.1.2.02.01.015,P/ VLR DE DESP ADMINISTRATIVO (030) HORA EXTRA...,2.614286,UN03,CR1002
5,31/07/2023,MANUAL,3.3.2.01.01.010,2.1.2.02.01.015,P/ VLR DE DESP ADMINISTRATIVO (100) ARREDONDAM...,0.282857,UN03,CR1002
6,31/07/2023,MANUAL,2.1.2.02.01.015,2.1.2.02.01.025,P/ VLR DE DESC DE FOLHA DE ADMINISTRATIVO (101...,332.127143,UN03,CR1002
7,31/07/2023,MANUAL,2.1.2.02.01.015,2.1.2.02.01.025,P/ VLR DE DESC DE FOLHA DE ADMINISTRATIVO (102...,16.520000,UN03,CR1002
8,31/07/2023,MANUAL,2.1.2.02.01.015,1.1.2.03.01.001,P/ VLR DE DESC DE FOLHA DE ADMINISTRATIVO (111...,1340.744286,UN03,CR1002
9,31/07/2023,MANUAL,2.1.2.02.01.015,3.3.2.01.01.010,P/ VLR DE DESC DE FOLHA DE ADMINISTRATIVO (113...,0.394286,UN03,CR1002
10,31/07/2023,MANUAL,2.1.2.02.01.015,1.1.2.03.01.002,P/ VLR DE DESC DE FOLHA DE ADMINISTRATIVO (115...,190.608571,UN03,CR1002
11,31/07/2023,MANUAL,2.1.2.02.01.015,3.3.2.01.02.010,P/ VLR DE DESC DE FOLHA DE ADMINISTRATIVO (123...,23.400000,UN03,CR1002
12,31/07/2023,MANUAL,2.1.2.02.01.015,4.9.2.01.01.001,P/ VLR DE DESC DE FOLHA DE ADMINISTRATIVO (125...,51.720000,UN03,CR1002
13,31/07/2023,MANUAL,2.1.2.02.01.015,3.3.2.01.01.010,P/ VLR DE DESC DE FOLHA DE ADMINISTRATIVO (141...,12.434286,UN03,CR1002
14,31/07/2023,MANUAL,2.1.2.02.01.015,3.3.2.01.02.030,P/ VLR DE DESC DE FOLHA DE ADMINISTRATIVO (145...,20.800000,UN03,CR1002
15,31/07/2023,MANUAL,2.1.2.02.01.015,4.4.1.01.12.007,P/ VLR DE DESC DE FOLHA DE ADMINISTRATIVO (153...,51.897143,UN03,CR1002
16,31/07/2023,MANUAL,2.1.2.02.01.015,4.9.2.01.01.005,P/ VLR DE DESC DE FOLHA DE ADMINISTRATIVO (161...,3.000000,UN03,CR1002
17,31/07/2023,MANUAL,2.1.2.02.01.015,1.1.2.07.01.007,P/ VLR DE DESC DE FOLHA DE ADMINISTRATIVO (162...,41.917143,UN03,CR1002
18,31/07/2023,MANUAL,2.1.2.02.01.015,2.1.2.02.02.045,P/ VLR DE DESC DE FOLHA DE ADMINISTRATIVO (190...,24.205714,UN03,CR1002
19,31/07/2023,MANUAL,3.3.2.01.01.040,2.1.2.02.01.030,P/ VLR DE DESC DE FOLHA DE ADMINISTRATIVO VALO...,280.955714,UN03,CR1002

In [1589]:
resultados = (associar_valor(valor) for valor in resumo['CR'])
resultado_final = pd.concat(resultados, ignore_index=True)

In [1590]:
valor_filtro = 'CR1002'
resultado_filtro = resultado_final[resultado_final['CR'] == valor_filtro]
resultado_filtro

,DATA,TIPO,DEBITO,CREDITO,DESCRICAO COMPLETA,VALOR,UNIDADE DE NEGOCIO,CR
0,31/07/2023,MANUAL,3.3.2.01.01.010,2.1.2.02.01.015,P/ VLR DE DESP ADMINISTRATIVO (001) SALARIO NO...,3509.812857,UN03,CR1002
1,31/07/2023,MANUAL,3.3.2.01.01.010,2.1.2.02.01.015,P/ VLR DE DESP ADMINISTRATIVO (004) DESCANSO S...,0.501429,UN03,CR1002
2,31/07/2023,MANUAL,2.1.2.02.02.010,2.1.2.02.01.015,P/ VLR DE DESP ADMINISTRATIVO (015) FERIAS,155.345714,UN03,CR1002
3,31/07/2023,MANUAL,2.1.2.02.02.010,2.1.2.02.01.015,P/ VLR DE DESP ADMINISTRATIVO (017) ADIC 1/3 D...,51.782857,UN03,CR1002
4,31/07/2023,MANUAL,3.3.2.01.01.010,2.1.2.02.01.015,P/ VLR DE DESP ADMINISTRATIVO (030) HORA EXTRA...,2.614286,UN03,CR1002
5,31/07/2023,MANUAL,3.3.2.01.01.010,2.1.2.02.01.015,P/ VLR DE DESP ADMINISTRATIVO (100) ARREDONDAM...,0.282857,UN03,CR1002
6,31/07/2023,MANUAL,2.1.2.02.01.015,2.1.2.02.01.025,P/ VLR DE DESC DE FOLHA DE ADMINISTRATIVO (101...,332.127143,UN03,CR1002
7,31/07/2023,MANUAL,2.1.2.02.01.015,2.1.2.02.01.025,P/ VLR DE DESC DE FOLHA DE ADMINISTRATIVO (102...,16.520000,UN03,CR1002
8,31/07/2023,MANUAL,2.1.2.02.01.015,1.1.2.03.01.001,P/ VLR DE DESC DE FOLHA DE ADMINISTRATIVO (111...,1340.744286,UN03,CR1002
9,31/07/2023,MANUAL,2.1.2.02.01.015,3.3.2.01.01.010,P/ VLR DE DESC DE FOLHA DE ADMINISTRATIVO (113...,0.394286,UN03,CR1002
10,31/07/2023,MANUAL,2.1.2.02.01.015,1.1.2.03.01.002,P/ VLR DE DESC DE FOLHA DE ADMINISTRATIVO (115...,190.608571,UN03,CR1002
11,31/07/2023,MANUAL,2.1.2.02.01.015,3.3.2.01.02.010,P/ VLR DE DESC DE FOLHA DE ADMINISTRATIVO (123...,23.400000,UN03,CR1002
12,31/07/2023,MANUAL,2.1.2.02.01.015,4.9.2.01.01.001,P/ VLR DE DESC DE FOLHA DE ADMINISTRATIVO (125...,51.720000,UN03,CR1002
13,31/07/2023,MANUAL,2.1.2.02.01.015,3.3.2.01.01.010,P/ VLR DE DESC DE FOLHA DE ADMINISTRATIVO (141...,12.434286,UN03,CR1002
14,31/07/2023,MANUAL,2.1.2.02.01.015,3.3.2.01.02.030,P/ VLR DE DESC DE FOLHA DE ADMINISTRATIVO (145...,20.800000,UN03,CR1002
15,31/07/2023,MANUAL,2.1.2.02.01.015,4.4.1.01.12.007,P/ VLR DE DESC DE FOLHA DE ADMINISTRATIVO (153...,51.897143,UN03,CR1002
16,31/07/2023,MANUAL,2.1.2.02.01.015,4.9.2.01.01.005,P/ VLR DE DESC DE FOLHA DE ADMINISTRATIVO (161...,3.000000,UN03,CR1002
17,31/07/2023,MANUAL,2.1.2.02.01.015,1.1.2.07.01.007,P/ VLR DE DESC DE FOLHA DE ADMINISTRATIVO (162...,41.917143,UN03,CR1002
18,31/07/2023,MANUAL,2.1.2.02.01.015,2.1.2.02.02.045,P/ VLR DE DESC DE FOLHA DE ADMINISTRATIVO (190...,24.205714,UN03,CR1002
19,31/07/2023,MANUAL,3.3.2.01.01.040,2.1.2.02.01.030,P/ VLR DE DESC DE FOLHA DE ADMINISTRATIVO VALO...,280.955714,UN03,CR1002

In [1591]:
resultado_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 272 entries, 0 to 271
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   DATA                272 non-null    object
 1   TIPO                272 non-null    object
 2   DEBITO              272 non-null    object
 3   CREDITO             272 non-null    object
 4   DESCRICAO COMPLETA  272 non-null    object
 5   VALOR               272 non-null    float64
 6   UNIDADE DE NEGOCIO  272 non-null    object
 7   CR                  272 non-null    object
dtypes: float64(1), object(7)
memory usage: 17.1+ KB

In [1592]:
export_xlsx = resultado_final.to_excel('output/resultado.xlsx', index=False)
export_csv = resultado_final.to_csv('output/resultado.csv', index=False)